# Generated by Django 4.0.8 on 2023-05-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, choices=[('Jersey', 'Jersey'), ('Hoodie', 'Hoodies'), ('Tshirt', 'T-shirt'), ('Sweater', 'Sweat-gear'), ('Watterbottle', 'Water-bottle')], max_length=150, null=True)),
                ('image', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField(max_length=500)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('count_in_stock', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-product_name',),
            },
        ),
    ]
