# Generated by Django 4.0.8 on 2023-05-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('logo', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
                ('about', models.TextField(max_length=500)),
                ('tag', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
    ]
