# Generated by Django 4.0.8 on 2023-05-08 18:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teamplayer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateField()),
                ('venue', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('kickoff', models.CharField(max_length=20)),
                ('away_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='teamplayer.team')),
                ('home_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='teamplayer.team')),
            ],
        ),
        migrations.CreateModel(
            name='FixtureResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team_result', models.PositiveIntegerField(default=0)),
                ('away_team_result', models.PositiveIntegerField(default=0)),
                ('MOTM', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teamplayer.player')),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_fixture', to='league.fixture')),
            ],
        ),
    ]
