# Generated by Django 4.0 on 2021-12-12 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_articles_headline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='updated',
            new_name='posted',
        ),
    ]
