# Generated by Django 4.0 on 2021-12-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_updated_articles_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='type',
            field=models.CharField(default='article', max_length=100, null=True),
        ),
    ]
