# Generated by Django 4.0 on 2021-12-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_articles_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ('-created',)},
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='story',
            new_name='content',
        ),
        migrations.AddField(
            model_name='articles',
            name='image_url',
            field=models.ImageField(blank=True, upload_to='uploads/% Y/% m/% d/'),
        ),
    ]
