# Generated by Django 4.0 on 2021-12-15 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_articles_caption_1_articles_caption_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='content',
            new_name='content_1',
        ),
    ]
