# Generated by Django 4.0.8 on 2022-11-29 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_fixtures_partner_team_player'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles',
            new_name='Article',
        ),
        migrations.RenameModel(
            old_name='Fixtures',
            new_name='Fixture',
        ),
    ]
