# Generated by Django 4.0.8 on 2022-12-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_player_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
