# Generated by Django 4.0.8 on 2022-12-11 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_article_image_1_alter_article_image_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixture',
            name='opponent',
        ),
        migrations.AddField(
            model_name='fixture',
            name='away_team',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='home.team'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='home_team',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='home.team'),
        ),
    ]
