# Generated by Django 4.0.8 on 2022-12-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_remove_fixture_opponent_fixture_away_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(blank=True, choices=[('J', 'Jersey'), ('H', 'Hoodies'), ('T', 'T-shirt'), ('S', 'Sweat-gear'), ('W', 'Water-bottle')], max_length=150, null=True),
        ),
    ]
