# Generated by Django 4.0.8 on 2023-01-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_smsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='count_in_stock',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='smsmodel',
            name='counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
