# Generated by Django 4.0.8 on 2023-01-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_product_count_in_stock_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
