# Generated by Django 4.0.8 on 2023-01-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_partner_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(blank=True, choices=[('Jersey', 'Jersey'), ('Hoodie', 'Hoodies'), ('Tshirt', 'T-shirt'), ('Sweater', 'Sweat-gear'), ('Watterbottle', 'Water-bottle')], max_length=150, null=True),
        ),
    ]
